### ISSUE TITLE
Setting properties for solaris services.

### ISSUE THREAD

**Issue by MarkGibbons** [livinginthepast/smf#17]
I'm building a bunch of new solaris 11 boxes. They need to have service properties set to manage things that used to be in files,DNS name resolution and NSS are two good examples. I'd rather not change settings with bash script resources. Getting the changes to be idempotent is a bit tricky. I'm in the process of adding a setprop action to a fork of this cookbook. Would you be amenable to including such an action if I put in a pull request?

Thanks,
Mark

**Comment by sax** [comment]
I'm closing this issue, as it's now covered here #18
