### ISSUE TITLE
smf/providers/default.rb:68: syntax error, unexpected keyword_end, expecting end-of-input

### ISSUE THREAD

**Issue by kramvan1** [livinginthepast/smf#20]
Bad commit?  smf/providers/default.rb:68: syntax error, unexpected keyword_end, expecting end-of-input

extra end keyword in there I believe?

**Comment by kramvan1** [comment]
https://github.com/livinginthepast/smf/blob/master/providers/default.rb#L68

**Comment by sax** [comment]
Try with the latest version.

This was introduced here: https://github.com/livinginthepast/smf/commit/89e6da9f7ac7be2824539f2e4b1077e0af8c5ccb. Bad me for releasing without running the tests!

**Comment by kramvan1** [comment]
thx, worked.
