### ISSUE TITLE
TypeError: superclass mismatch for class Helper

### ISSUE THREAD

**Issue by flatrocks** [livinginthepast/smf#21]
After updating from 2.2.1 to 2.2.3, the first, very basic test in a large chefspec suite:
```
    describe "the temp dir" do
      it "is created" do
        expect(subject).to create_directory("/home/maxwell/temp")
      end
    end
``` 
...fails with this error: 
 ```
     Failure/Error: end.converge(described_recipe) }
     TypeError:
       superclass mismatch for class Helper
     # /<berkshelf directory>/cookbooks/smf/libraries/helper.rb:5:in `<module:SMFManifest>'
     # /<berkshelf directory>/cookbooks/smf/libraries/helper.rb:1:in `<top (required)>'
```
Reverting to 2.2.1 brings back joy and all the green dots.  I am sure that more info would be helpful but I am not sure what.  Please advise about what additional info might be helpful.

**Comment by cmluciano** [comment]
I'm seeing this error too. I'm thinking it might be related to https://github.com/livinginthepast/smf/commit/89e6da9f7ac7be2824539f2e4b1077e0af8c5ccb.

**Comment by wenchma** [comment]
this error should be urgent issue, the jenkins failed a lot with chef spec unit.

**Comment by cmluciano** [comment]
My guess is a name clash of Helper

**Comment by sax** [comment]
It's probably the Struct. Something is reloading classes, reloading Helper. That defines a new struct, which does not match the old one.

**Comment by sax** [comment]
I ran into this problem in the local rspecs, but was running into other (unrelated) issues on my workstation running test-kitchen. I've finally sorted those out, so should have a fix soon.

**Comment by sax** [comment]
Can you try with 2.2.4?

**Comment by flatrocks** [comment]
Excellent!  2.2.4 solved this for me.

**Comment by sax** [comment]
Awesome. Yeah, my bad. I've started using the Struct pattern all over the place, and only recently realized the problem it was creating in tests.
