### ISSUE TITLE
smf berks vendor error?

### ISSUE THREAD

**Issue by HiroyoshiMori** [livinginthepast/smf#22]
Hi eric.

I got errors what i sent in twitter.
the below log was what i got.

if this is not "smf error", can you tell me where i should ask?
but still if i change "long_description" value original to "", berks vendor will finish successfully.

-----
Resolving cookbook dependencies...
Fetching 'suphp' from git://github.com/TheSerapher/chef-suphp.git (at master)
Fetching cookbook index from https://supermarket.getchef.com...
Using 7-zip (1.0.2)
Using apache2 (3.0.1)
Using apt (2.6.1)
Using ark (0.9.0)
Using build-essential (2.1.3)
Using chef-sugar (2.5.0)
Using chef_handler (1.1.6)
Using database (4.0.3)
Using dovecot (2.0.0)
Using hostname (0.3.0)
Using hostsfile (2.4.5)
Using iis (4.1.0)
Using iptables (0.14.1)
Using logrotate (1.9.0)
Using mysql (6.0.15)
Using ohai (2.0.1)
Using onddo-spamassassin (0.2.0)
Using openssl (4.0.0)
Using php (1.5.0)
Using postfix-dovecot (0.3.0)
Using postfix-full (0.1.2)
Using postfixadmin (0.2.0)
Using postgresql (3.4.18)
Using rbac (1.0.2)
Using resolver (1.2.0)
Using simple_iptables (0.7.1)
Installing smf (2.2.5) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io/api/v1)
Using sudo (2.7.1)
Using suphp (0.1.3) from git://github.com/TheSerapher/chef-suphp.git (at master)
Using windows (1.36.6)
Using xml (1.2.13)
Using yum (3.5.3)
Using yum-epel (0.6.0)
Using yum-ius (0.4.0)
Using yum-mysql-community (0.1.13)
Using yum-repoforge (0.4.0)
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `encode': "\x94" followed by " " on Windows-31J (Encoding::InvalidByteSequenceError)
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `new'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:473:in `from_json'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:29:in `from_json'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook.rb:36:in `from_path'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cached_cookbook.rb:15:in `from_store_path'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cookbook_store.rb:86:in `cookbook'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cookbook_store.rb:67:in `import'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cookbook_store.rb:30:in `import'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/installer.rb:106:in `block in install'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/downloader.rb:38:in `block in download'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/downloader.rb:35:in `each'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/downloader.rb:35:in `download'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/installer.rb:105:in `install'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/future.rb:104:in `value'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/future.rb:68:in `value'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/installer.rb:175:in `map'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/installer.rb:175:in `install_from_universe'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/installer.rb:39:in `run'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/berksfile.rb:374:in `install'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/berksfile.rb:583:in `block in vendor'
	from C:/opscode/chef/embedded/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/berksfile.rb:581:in `vendor'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cli.rb:387:in `vendor'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cli.rb:52:in `dispatch'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cli.rb:27:in `execute!'
	from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/bin/berks:5:in `<top (required)>'
	from C:/opscode/chef/embedded/bin/berks:23:in `load'
	from C:/opscode/chef/embedded/bin/berks:23:in `<main>'
E, [2015-03-10T10:18:16.768290 #39324] ERROR -- : Actor crashed!
Encoding::InvalidByteSequenceError: "\x94" followed by " " on Windows-31J
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `encode'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `new'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:473:in `from_json'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:29:in `from_json'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook.rb:36:in `from_path'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cached_cookbook.rb:15:in `from_store_path'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cookbook_store.rb:86:in `cookbook'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cookbook_store.rb:67:in `import'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/cookbook_store.rb:30:in `import'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/installer.rb:106:in `block in install'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/downloader.rb:38:in `block in download'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/downloader.rb:35:in `each'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/downloader.rb:35:in `download'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/berkshelf-3.2.3/lib/berkshelf/installer.rb:105:in `install'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
-----

**Comment by CloCkWeRX** [comment]
https://tickets.opscode.com/browse/COOK-522
and
https://github.com/berkshelf/berkshelf-api/issues/112

Its basically "authorization` ��� What manage" and friends.
