### ISSUE TITLE
Remove 'recommends' from metadata

### ISSUE THREAD

**Issue by tpetchel** [livinginthepast/smf#23]
This cookbook `recommends` the `resource-control` cookbook:

https://github.com/livinginthepast/smf/blob/master/metadata.rb#L13

This breaks a basic usage scenario for Berkshelf:

https://github.com/berkshelf/berkshelf/issues/1404

Aside from whether or not this is a Berkshelf or Supermarket bug, can we remove the `recommends` line? Seems that `recommends` was never implemented.

**Comment by sax** [comment]
I'm seeing other people switching from `recommends` to `suggests`. I just pushed a change that does the same... does this fix things for you?

**Comment by tpetchel** [comment]
@sax yes, that unblocks my scenario. Thanks so much for the fast turnaround!
