### ISSUE TITLE
default value 'evolving' gives error on attribute stability even though evolving is a part of permissible values

### ISSUE THREAD

**Issue by wallydrag** [livinginthepast/smf#26]
Default value "Evolving" is invalid for property stability of resource smf. In Chef 13 this will become an error: Option stability must be equal to one of: Standard Stable Evolving Unstable External Obsolete!  You passed "Evolving".. at 1 location:
           - /tmp/kitchen/cache/cookbooks/smf/resources/default.rb:39:in `class_from_file'
         chef_gem[activesupport] chef_gem compile_time installation is deprecated at 1 location:

**Comment by sax** [comment]
Fixed by #27.
