### ISSUE TITLE
On RHEL 6, "/sbin/service mysql-default reload" fails

### ISSUE THREAD

**Issue by nkadel-skyhook** [livinginthepast/smf#28]
On RHEL 6 and CentOS 6, after configuring a new mysql-default instance, reloading the daemon fails.
- /etc/init.d/mysql-default reload #  Works just fine
- /sbin/service mysql-default reload # fails with meswsages below:
- /sbin/service mysql-default reload
  /usr/bin/mysqladmin: connect to server at 'localhost' failed
  error: 'Access denied for user 'root'@'localhost' (using password: NO)'
  Reloading mysql-default                                    [FAILED]

I've broken it down to this command run by /sbin/service:
-  env -i PATH=/sbin:/usr/sbin:/bin:/usr/bin TERM=xterm /etc/init.d/mysql-default reload

It loooks like the env command is clearing "HOME=/root", which is killing access to /root/.my.cnf. I'm not sure what the best way is to activate those stored credentials for the init script.

**Comment by sax** [comment]
Are you sure you've filed this issue in the correct repository? SMF is the service management facility for Solaris and Illumos kernels.

**Comment by nkadel-skyhook** [comment]
Gahh, sorry, I had smf open for other reasons. I'l close it!
